### ISSUE TITLE
DF website species checklist

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/BRCtracker#37]
A checklist has been installed on the website, based on a recent copy of the MapMate species dictionary.

To do:
- [ ] provide a means of editing and updating the checklist
- [ ] make it easier to link to particular species e.g. when adding photos
- [ ] provide a way of browsing and searching the checklist

At the moment we are quite a long way from replicating the browse, search and download facilities available on the old DF website, and if DF wish to replicate this it is likely that some checklist development will need to be done as a separate project, outside the scope of the current work to establish the website.

**Comment by kitenetter** [comment]
A new version of the MapMate checklist is in:
W:\PYWELL_SHARED\Pywell Projects\BRC\_BRC_projects\Dipterists Forum website\Checklist documents\MapMate Diptera 2018_06_21_edited.xlsx

If it is possible to remove the checklist we imported and few months ago, and replace it with this one, we may then be able to keep it up to date via manual updates in future.

Suggestion: can we set up a view of this as a fairly simply table, with filter boxes that allow particular families or species to be found? A bit similar to this example on the Beetle Recording site:
http://www.coleoptera.org.uk/biographical-dictionary

**Comment by BirenRathod** [comment]
I have updated the species from new version of MapMate checklist.

**Comment by kitenetter** [comment]
To re-visit following move to Pantheon.
